language: python
dist: xenial
sudo: true

python:
  - 3.9

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VERBOSITY=-1

Install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pipenv run flake8
  - pipenv run pytest --cov=appweb

after_success:
  - pipenv run codecov