language: python
dist: xenial
sudo: true

python:
  - 3.9

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VERBOSITY=-1

Install:
  - pip install pipenv
  - pipenv sync

script:
  - pipenv run flake8
